### PR TITLE
FIX revert to cascading permission checks for canWorkflowPublish

### LINKED ISSUE #333: Admin can not save an applied work definition to a page (bad request)
Admin can not save an applied work definition to a page (bad request) (saved but error message)

### PR DESCRIPTION
**Pull request by raissanorth**
SiteTree::canPublish leverages DataExtensions to delegate permission checking,
and falling back to checking for administrative or canEdit priviliges when
NULL is returned, and strictly NULL (ie. not FALSE or 0). However
WorkflowDefinition::canWorkflowPublish short circuits this by explicitly
returning FALSE when a NULL value is detected, meaning SiteTree's default
fallbacks are never checked. This had an unfortunate side effect of not letting
and user with ADMIN permissions `Save & Publish` a page while applying a workflow
for the first time. By no longer short circuiting and re-instating the default
cascade of checks, we resolve this fatal error.

Resolves #333 

Thank you @nyeholt for your help!

### CODE REVIEW

File: src/DataObjects/WorkflowDefinition.php [hunk 1]
```diff
@@ -482,12 +482,7 @@ public function incomingTitle()
      */
     public function canWorkflowPublish($member, $target)
     {
-        $publish = $this->extendedCan('canWorkflowPublish', $member, $target);
-
-        if (is_null($publish)) {
-            return false;
-        }
-        return $publish;
+        return $this->extendedCan('canWorkflowPublish', $member, $target);
```
Comment (tractorcow) [inline src/DataObjects/WorkflowDefinition.php]: If no extensions modify this permission check, it will default to null. Unfortunately, `(bool)null === false` so the can check might still incorrectly evaluate to false.

**Comment by tractorcow** [comment]
Important comment on https://github.com/symbiote/silverstripe-advancedworkflow/issues/333#issuecomment-362972994

I think we still need another permission check in here.

File: src/DataObjects/WorkflowDefinition.php (hunk 1 above)
Comment (tractorcow) [inline src/DataObjects/WorkflowDefinition.php]: I think we should still fail to `ADMIN` check in case `$publish` is null (rather than return false).

Comment (tractorcow) [reply src/DataObjects/WorkflowDefinition.php]: See reasoning at https://github.com/symbiote/silverstripe-advancedworkflow/issues/333#issuecomment-362972994
